name: Test and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Create .env
      run: echo ${{secrets.DOT_ENV}} > .env
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' 'node_modules*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: hunter
        environment_name: hunter-dev
        version_label: ${{ github.event.repository.pushed_at}}
        region: ap-northeast-1
        deployment_package: deploy.zip
